win32:LIBSDIR		= $$(SystemDrive)/QLC
unix:LIBSDIR		= /usr/lib

win32:PLUGINDIR		= $$LIBSDIR/Plugins
unix:PLUGINDIR		= $$LIBSDIR/qlc

unix:INPUTPLUGINDIR	= $$PLUGINDIR/input
win32:INPUTPLUGINDIR	= $$PLUGINDIR/Input

unix:OUTPUTPLUGINDIR	= $$PLUGINDIR/output
win32:OUTPUTPLUGINDIR	= $$PLUGINDIR/Output
